title: "Bitsflippin"
description: "Boutique Technology Consulting & IT Hardware"
images: 
  - "images/hero-image.png"

logo: "arrow-up.png"

favicons:
  themeColor: "#FFFFFF"
  backgroundColor: "#FFFFFF"
  faviconColor: "#000000"

social:
  dribbble: "#"
  instagram: "#"
  facebook: "#"
  twitter: "#"

location:
  - "California USA"
  - "Hyderabad, India"
  - "Pondicherry, India"

contact:
  - "hello@bitsflippin.com"
  - "+91 8866015116"

copyright: "Â© 2025 Bitsflippin All Rights Reserved"

